name: Github Action - pull request types (basic)

run-name: Executando - ${{github.event_name}}

on:
  pull_request:  
    types:
      - opened
      - reopened
      - closed  
  
jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
            echo "apenas na branch main"
