name: Github Action - pull request (basic)

run-name: Executando - ${{github.event_name}}

on:
  pull_request:  
    branches:
      - developer
  
jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
            echo "apenas na branch main"
