name: Github Action - paths  (basic)
run-name: Executando - ${{github.event_name}}

on:
  push:
    paths:
     - '**.py'
     - '**.c'
jobs:
  on-push:
   runs-on: ubuntu-latest
   steps:
     -  name: Comentario
        run: echo "arquivos python e C"
