name: Github Action - paths (basic)
run-name: Executando - ${{github.event_name}}

on:
  push:
    branches:
      - main
      - developer
    paths:
      - '**.py'

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: echo "arquivos python e C, <main-branch>"
