name: Github Action  Jobs

run-name: Usando Jobs

on: [push, workflow_dispatch]
jobs:
 test_unit:
  runs-on: ubuntu-latest
  steps:
   - name: usando o workFlow run
     run: |
          echo "Inicial"

 test_api:
  needs: test_unit
  runs-on: ubuntu-latest
  steps:
    - name: usando o workFlow run
      run: |
           echo "Teste Api"

 test_erro:
  needs:[test_api, test_unit]
  runs-on: ubuntu-latest
  steps:
    - name: usando o workFlow run
      run: |
          echo "Teste erro"
