nane: Trigger Terceiro
run-name: executando  terceiro

on: [push,workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Terceiro Iniciado
       run: |
         echo "Trabalha terceiro"
