name: Workflow condicionais
 
run-name:  condicionais ${{github.event_name}}
on: [push, workflow_dispatch] 


jobs:
 on-push-only:
  if: ${{github.event_name == 'push'}}
  runs-on: ubuntu-latest
  steps:
   - name: inciando
     run: |
      echo "iniciado"


on_workflow_dispatch_only:
 if: ${{github.event_name == 'workflow_dispatch'}}
 runs-on: ubuntu-latest
 steps:
  - name: comentario...
    run: |
     echo "...."
